version: "2.1"
services:
  java-testapp:     
    build: ./Java-testapp 
    ports:
      - "8080:8080"  
    container_name: java-app
    healthcheck:
      #test: ["CMD", "lsof", "-i:8080"]
      test: grep -i "Server startup" /usr/local/tomcat/logs/catalina.`date +"%Y-%m-%d"`.log || exit 1
      #test: ["CMD-SHELL", "grep -i", "Server startup", "/usr/local/tomcat/logs/catalina.`date +"%Y-%m-%d"`"]
      interval: 5s
      timeout: 2s
      retries: 3

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    container_name: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
  
  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    container_name: selenium-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"

  selenium-test:
    build: ./node  
    restart: always
    container_name: selenium-test
    volumes:
      - ./test:/home/node/test:rw
      - ./report:/home/node/report:rw
    depends_on:
      java-testapp:
        condition: service_healthy

    working_dir: /home/node/test
    command : selenium-side-runner Test-session-selenium.side --server http://selenium-hub:4444/wd/hub -c "browserName='chrome'" --output-directory=/home/node/report 

